name: llm-poking-env
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=24.0
  - python=3.12.2
  - pip:
      - accelerate==0.28.0
      - bitsandbytes==0.43.0
      - datasets==2.18.0
      - faiss-cpu==1.8.0
      - ipywidgets==8.1.2
      - langchain==0.1.13
      - notebook==7.1.2
      - sentence-transformers==2.6.1
      - torch==2.2.1
      - transformers==4.39.1
